os:
  - linx
  - osx

language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

sudo: false

addons:
  apt:
    packages:
    - gcc
    - g++

script:
  - ./run_tests_travis.sh

notifications:
  email:
    - andreas.heger@gmail.com
